#ifndef IOCTL_MODULE_H
#define IOCTL_MODULE_H

#include <linux/ioctl.h>

#define MAJOR_NUM (229)

/*
#define IOCTL_ADD_VECTOR _IORW(MAJOR_NUM, 0, char *)

#define IOCTL_REMOVE_VECTOR _IORW(MAJOR_NUM, 1, char *)

#define IOCTL_ADD_SYSCALL_TO_VECTOR _IORW(MAJOR_NUM, 2, char *)

#define IOCTL_REMOVE_SYSCALL_REMOVE_FROM_VECTOR _IORW(MAJOR_NUM, 3, char *)

#define IOCTL_ASSIGN_VECTOR_TO_PROCESS _IORW(MAJOR_NUM, 4, char *)

#define IOCTL_GET_VECTOR_ID_OF_PROCESS _IORW(MAJOR_NUM, 5, char *)

#define IOCTL_GET_INFO _IOWR(MAJOR_NUM, 6, char *)
*/

#define IOCTL_SYSCALL_TBL_ADD_VECTOR _IOWR(MAJOR_NUM, 1, char *)
#define IOCTL_SYSCALL_TBL_REMOVE_VECTOR _IOWR(MAJOR_NUM, 2, char *)

#define IOCTL_SYSCALL_TBL_ADD_SYSCALL_TO_VECTOR _IOWR(MAJOR_NUM, 4, char *)
#define IOCTL_SYSCALL_TBL_REMOVE_SYSCALL_FROM_VECTOR _IOWR(MAJOR_NUM, 8, char *)


#define IOCTL_SYSCALL_TBL_ASSIGN_VECTOR_TO_PROCESS _IOWR(MAJOR_NUM, 16, char *)


#define IOCTL_SYSCALL_TBL_GET_VECTOR_ID_OF_PROCESS _IOWR(MAJOR_NUM, 32, char *)

#define IOCTL_SYSCALL_TBL_GET_INFO _IOWR(MAJOR_NUM, 64, char *)

#define IOCTL_SYSCALL_TBL_BLOCK _IOWR(MAJOR_NUM, 128, char *)
#define IOCTL_SYSCALL_TBL_UNBLOCK _IOWR(MAJOR_NUM, 256, char *)

#endif
